name: "Prepare PMC Instance For Automation Test Run"
secrets:
  PMC_DB_CONNECTION_STRING:
    required: true
    type: string
  ACCEPTED_DOMAIN:
    default: "example.com"
    type: string


runs:
  using: "composite" 
  steps:
    - name: Enable Admin Account
      run: ./${{ github.action_path }}/EnableAdminAccount.ps1 -DbConnectionString ${{ inputs.PMC_DB_CONNECTION_STRING }}
      shell: pwsh

    - name: Add Accepted Domain
      run: ./${{ github.action_path }}/AddAcceptedDomain.ps1 -DbConnectionString ${{ inputs.PMC_DB_CONNECTION_STRING }} -AcceptedDomain ${{ inputs.ACCEPTED_DOMAIN }}
      shell: pwsh

    - name: Enable API Key Client
      run: ./${{ github.action_path }}/EnableApiKeyClient.ps1 -DbConnectionString ${{ inputs.PMC_DB_CONNECTION_STRING }}