name: "Sanitize PMC Instance Data"
secrets:
  PMC_DB_CONNECTION_STRING:
    required: true
    type: string

runs:
  using: "composite" 
  steps:
    - name: Sanitize PMC Instance Database
      run: Invoke-Sqlcmd -ConnectionString ${{ secrets.PMC_DB_CONNECTION_STRING }} -InputFile "${{ github.action_path }}/sanitize-pmc-instance.sql"
      shell: pwsh