name: "Sanitize PMC Instance Data"
inputs:
  PMC_DB_CONNECTION_STRING:
    required: true
    type: string

runs:
  using: "composite" 
  steps:
    - name: Sanitize PMC Instance Database
      run: Invoke-Sqlcmd -ConnectionString "${{ inputs.PMC_DB_CONNECTION_STRING }}" -InputFile "${{ github.action_path }}/sanitize-pmc-instance.sql"
      shell: pwsh