name: 'Runner'
on:
  workflow_dispatch:
    inputs:
      SANITIZE:
        description: "Should sanitize PMC instance?"
        required: true
        type: boolean
        default: false
      PMC_DB_CONNECTION_STRING:
        description: "PMC DB Connection String"
        required: true
        type: string

jobs:
  prepare-instance:
    name: Prepare PMC instance for automation testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 

    - name: Mask Sensitive Input
      run: Write-Output "::add-mask::${{ inputs.PMC_DB_CONNECTION_STRING }}"
      shell: pwsh

    - name: Sanitize PMC Instance Data
      uses: ./.github/actions/sanitize-pmc-instance
      with:
        PMC_DB_CONNECTION_STRING: ${{ inputs.PMC_DB_CONNECTION_STRING }}
      if:  ${{ inputs.SANITIZE }}

    - name: Onboard PMC Instance for Automation Test Run
      uses: ./.github/actions/onboard-pmc-automation
      with:
        PMC_DB_CONNECTION_STRING: ${{ inputs.PMC_DB_CONNECTION_STRING }}
