name: 'Test Reporter Test'
on:
  workflow_dispatch:

jobs:
  publish-results:
    name: Report Test Results
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Test
      run: |
        echo "test"
        cd ${{ github.workspace }}\.github\workflows
        ls -al

    - name: Publish test results summary
      uses: dorny/test-reporter@e8e27361afb5e7def8b7938009be0726e1bbbf16
      with:
        name: Test Results
        path: ${{ github.workspace }}\.github\workflows\results.xml
        reporter: jest-junit
        use-actions-summary: true 
        only-summary: false
        fail-on-error: true 
        list-suites: all
        list-tests: all
