name: 'Runner'
on:
  workflow_dispatch:
    inputs:
      SANITIZE:
        description: "Should sanitize PMC instance?"
        required: true
        type: boolean
        default: false
      PMC_DB_CONNECTION_STRING:
        description: "PMC DB Connection String"
        required: true
        type: string

jobs:
  sanitize-instance:
    name: Sanitize PMC Instance Data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 

    - name: Local Action Call
      uses: ./.github/actions/sanitize-pmc-instance
      with:
        PMC_DB_CONNECTION_STRING: ${{ secrets.PMC_DB_CONNECTION_STRING }}
      if:  ${{ inputs.SANITIZE }}

  onboard-instance:
    name: Onboard PMC Instance for Automation Test Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./.github/actions/onboard-pmc-automation
      with:
        PMC_DB_CONNECTION_STRING: ${{ secrets.PMC_DB_CONNECTION_STRING }}
