name: 'Test Reporter Test'
on:
  workflow_dispatch:

jobs:
  prepare-instance:
    name: Prepare PMC instance for automation testing
    runs-on: windows-2022
    environment: 'automation'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Publish backend test results summary
      uses: dorny/test-reporter@e8e27361afb5e7def8b7938009be0726e1bbbf16
      if: ${{ !cancelled() }}
      with:
        name: Backend E2E Tests
        path: ${{ github.workspace }}/.github/results.xml
        reporter: jest-junit
        use-actions-summary: true 
        only-summary: false
        fail-on-error: true 
        list-suites: all
        list-tests: all
