name: 'Test Reporter Test'
on:
  workflow_dispatch:

jobs:
  publish-results:
    name: Report Test Results
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Test
      run: |
        echo "test"
        cd ${{ github.workspace }}/.github/workflows
        ls -al

    - name: publish Cypress tests results summary
      uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 #v2.4
      if: always()
      with:
        paths: ${{ github.workspace }}/.github/workflows/results.xml
        show: "all"
